[paths]
wps = 'c:\Users\<YOUR_USER_NAME>\AppData\Local\Kingsoft\WPS Office\ksolaunch.exe'
word = 'C:\Program Files\Microsoft Office\root\Office16\WINWORD.EXE'
powerpoint = 'C:\Program Files\Microsoft Office\root\Office16\POWERPNT.EXE'
excel = 'C:\Program Files\Microsoft Office\root\Office16\EXCEL.EXE'